name: Build Android APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Validate Supabase secrets
        run: |
          node -e "
          const url = '${{ secrets.SUPABASE_URL }}';
          const key = '${{ secrets.SUPABASE_ANON_KEY }}';
          
          console.log('🔍 Validating Supabase secrets...');
          
          if (!url || url.length < 10) {
            console.error('❌ SUPABASE_URL is missing or invalid');
            process.exit(1);
          }
          if (!key || key.length < 10) {
            console.error('❌ SUPABASE_ANON_KEY is missing or invalid');
            process.exit(1);
          }
          
          console.log('✅ SUPABASE_URL: ' + url.substring(0, 15) + '...' + url.slice(-10));
          console.log('✅ SUPABASE_ANON_KEY: ' + key.substring(0, 10) + '...' + key.slice(-10));
          console.log('✅ Secrets validation passed');
          "
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate env.js with Supabase credentials and API URLs
        run: |
          cat > env.js << 'EOF'
          export const SUPABASE_URL = "${{ secrets.SUPABASE_URL }}";
          export const SUPABASE_ANON_KEY = "${{ secrets.SUPABASE_ANON_KEY }}";
          export const SLEEP_API_URL = "${{ secrets.SLEEP_API_URL }}";
          EOF
          echo "✅ Generated env.js with credentials and API URLs"
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Generate Android files
        run: npx expo prebuild --platform android --clean
      
      - name: Verify Kotlin native files were generated
        run: |
          echo "🔍 Verifying native foreground service Kotlin files..."
          
          KOTLIN_DIR="android/app/src/main/java/com/polarsensor/app"
          
          if [ ! -f "$KOTLIN_DIR/NativeForegroundService.kt" ]; then
            echo "❌ NativeForegroundService.kt NOT FOUND"
            exit 1
          else
            echo "✅ NativeForegroundService.kt exists"
          fi
          
          if [ ! -f "$KOTLIN_DIR/ForegroundServiceModule.kt" ]; then
            echo "❌ ForegroundServiceModule.kt NOT FOUND"
            exit 1
          else
            echo "✅ ForegroundServiceModule.kt exists"
          fi
          
          if [ ! -f "$KOTLIN_DIR/ForegroundServicePackage.kt" ]; then
            echo "❌ ForegroundServicePackage.kt NOT FOUND"
            exit 1
          else
            echo "✅ ForegroundServicePackage.kt exists"
          fi
          
          echo "🔍 Checking MainApplication.kt for package registration..."
          MAIN_APP="android/app/src/main/java/com/polarsensor/app/MainApplication.kt"
          
          if ! grep -q "ForegroundServicePackage" "$MAIN_APP"; then
            echo "❌ ForegroundServicePackage NOT registered in MainApplication.kt"
            echo "MainApplication.kt contents:"
            cat "$MAIN_APP"
            exit 1
          else
            echo "✅ ForegroundServicePackage is registered in MainApplication.kt"
          fi
          
          echo "✅ All native service files verified successfully"
      
      - name: Build APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon
      
      - name: Inspect APK bundle for credentials
        run: |
          echo "🔍 Inspecting APK bundle for Supabase credentials..."
          
          # Extract the APK
          unzip -q android/app/build/outputs/apk/release/app-release.apk -d /tmp/apk-inspect
          
          # Find and check the main bundle
          BUNDLE=$(find /tmp/apk-inspect -name "index.android.bundle" | head -n 1)
          
          if [ -z "$BUNDLE" ]; then
            echo "⚠️ Could not find index.android.bundle in APK"
          else
            URL_FRAGMENT="${{ secrets.SUPABASE_URL }}"
            URL_FRAGMENT="${URL_FRAGMENT:0:20}"
            
            if grep -q "$URL_FRAGMENT" "$BUNDLE"; then
              echo "✅ Supabase URL found in bundle"
            else
              echo "❌ Supabase URL NOT found in bundle - injection failed!"
              exit 1
            fi
          fi
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 30
